### ISSUE TITLE
PHP syntax highlight problem with nested code

### ISSUE THREAD

**Issue by heavybeard** [equinusocio/material-theme#867] opened 2016-06-13 07:18 UTC
Hi!
I noticed this problem already in the previous release. I never opened a issue because you were modifying the code (I saw some commit).

It seems that the nest after 4 tab break the highlight

![image](https://cloud.githubusercontent.com/assets/12038447/15999685/9aee395a-3147-11e6-9bce-8334fb54eb4a.png)

This is the testing code

```php
Route::group(['prefix' => '1st-level'], function () {
    Route::group(['prefix' => '2nd-level'], function () {
        Route::group(['prefix' => '3rd-level'], function () {
            /** Comment */
            Route::group(['prefix' => '4th-level'], function () {
                Route::get('/', 'FooController@getFoos');
            });
        });
    });
});

Route::group(['prefix' => '1st-level'], function () {
    Route::group(['prefix' => '2nd-level'], function () {
        Route::group(['prefix' => '3rd-level'], function () {
            Route::group(['prefix' => '4th-level'], function () {
                /** Comment */
                Route::group(['prefix' => '5th-level'], function () {
                    Route::get('/', 'FooController@getFoos');
                });
            });
        });
    });
});

Route::group(['prefix' => '1st-level'], function () {
    Route::group(['prefix' => '2nd-level'], function () {
        Route::group(['prefix' => '3rd-level'], function () {
            Route::group(['prefix' => '4th-level'], function () {
                Route::group(['prefix' => '5th-level'], function () {
                    /** Comment */
                    Route::group(['prefix' => '6th-level'], function () {
                        Route::get('/', 'FooController@getFoos');
                    });
                });
            });
        });
    });
});
```

**Comment by equinusocio** [comment] 2016-06-13 07:48
No problems with material theme 3 and both BabelJs Package or the built-in js package:
<img width="643" alt="screen shot 2016-06-13 at 09 47 17" src="https://cloud.githubusercontent.com/assets/10454741/16000316/f61496ea-314b-11e6-846a-ba2578cc7dc9.png">
<img width="606" alt="screen shot 2016-06-13 at 09 47 42" src="https://cloud.githubusercontent.com/assets/10454741/16000317/f61b3fcc-314b-11e6-8f47-a3bd91d7fb49.png">

This is also a duplicate of #813

**Closed by equinusocio** 2016-06-13 07:48 UTC

**Comment by heavybeard** [comment] 2016-06-13 08:02
Ok thank you very much. I've downgraded sublime and now works.

I suggest to add this Sublime bug on Known Issues Readme section https://github.com/equinusocio/material-theme#known-issues
