### ISSUE TITLE
Strange white bar on top of the sidebar!

### ISSUE THREAD

**Issue by huyle2607** [equinusocio/material-theme#518] opened 2015-11-25 02:32 UTC
I don't know what is wrong with my Sublime text 3.When I use your Material theme, everything seems to be awesome. However, there is a tiny problem. As I look at your theme screenshot, I don't see any white bar on the top of the sidebar but mine has it. I don't know how to remove it. Please tell me it's just one of your designed thing.
![screenshot_1](https://cloud.githubusercontent.com/assets/15210474/11386782/567c5fb0-9357-11e5-9ae0-806ec0d4c8c8.png)

**Comment by equinusocio** [comment] 2015-11-25 09:15
This is the first time i see this issue and i cant reproduce it. You can share your preferences? and give more details:

- Have you restarted ST?
- Platform?
- ST build?
- Have you tried to reinstall the theme? (both manually and package control)

**Comment by alvin2671994** [comment] 2015-11-25 09:52
Actually the first time I use this theme, it worked perfectly but because of some problems I had to uninstall Sublime text. And this annoy little thing has appeared since I installed back the Sublime text. I have restarted it for many time but it doesn't work.
I use Windows 7 and Sublime text 3 (Build 3083)

**Comment by imoby** [comment] 2015-11-26 01:39
@alvin2671994 did you try installing a different theme (such as preap) and see if it does the same thing. It will hopefully help root out if it is specifically related to material theme. Always restart when installing new themes btw.

**Comment by alvin2671994** [comment] 2015-11-26 02:26
@imoby  I did! When I installed a different theme, that bar was gone. Actually I'm starting to think there are some problems with my Sublime text cause some themes that I installed, it had some problems with the UI too. Is it because of the version of Sublime text?!

**Comment by Revod** [comment] 2015-11-26 04:19
did you try removing the folder, closing st and open again and add the folder again?

**Comment by alvin2671994** [comment] 2015-11-26 05:29
@Revod  You mean remove all the Sublime text folder completely from computer?

**Comment by alvin2671994** [comment] 2015-11-26 05:30
@Revod  You mean remove all the Sublime text folder completely from computer?

**Comment by SG-Github** [comment] 2015-11-26 05:54
May not have anything to do with your issue, but I had issues when switching between different color schemes and themes.

I uninstalled themes, colors, highlighters and every package i added after installing ST3 and problem persisted.  I renamed  folder I placed ST3 ( I'm using portable version ).  Problem persisted.  I copied folders ST3 to external drive then deleted all color and theme packages I installed.  Problem persisted.  I remove all ST3 folders and reinstalled ST3.  Problem persisted.  I noticed I didn't have to reinitializw license which was strange.  Then I discovered there are several folders that were caching license, packages I downloaded and my user serttings.  I deleted those items and problem went away.  I forgot what folder name was, but I did scan for sublime aND it found those caching folders.  I'm on Win 8.1 and always use portable version of ST3 and python...

While not same issue, fact that issue is persistent even after removing and reinstalling may be similar issue resulting from items being cached.  Again, I am on Win 8.1 platform.

**Comment by alvin2671994** [comment] 2015-11-30 03:51
@SG-Github  Thank you for your help. Actually I think I did those things already 'cause when I uninstalled  the ST3 I also looked for all the hidden ST3 folder in AppData folder (I'm using Win 7). However this problem was still there. I think I have to live with it then. It looks kinda annoyed but I have no choice.

**Comment by equinusocio** [comment] 2015-11-30 06:47
@alvin2671994 You see the bar only when open a peiect?

**Comment by alvin2671994** [comment] 2015-11-30 13:32
@equinusocio  Yup! Only when I open the Sidebar. When it's close, everything is perfect.

**Comment by equinusocio** [comment] 2015-11-30 13:36
Try to open a project and make a new workspace.

Under the project menu try this:
![screen shot 2015-11-30 at 14 35 13](https://cloud.githubusercontent.com/assets/10454741/11472858/a872ebd8-976f-11e5-98d1-d32599768a92.png)

**Comment by huyle2607** [comment] 2015-11-30 14:53
It's still there!

**Comment by equinusocio** [comment] 2015-12-01 18:55
I really don't know how help you. This is really strange. Maybe try to post your preferences

**Comment by huyle2607** [comment] 2015-12-02 02:35
@equinusocio  Ok, thank you very much for your help, though! Really appreciate it.

**Comment by equinusocio** [comment] 2015-12-02 15:29
This glitch appear also with other themes?

**Comment by Revod** [comment] 2015-12-03 01:00
Are you tried make a backup of your st with [PackageSync](https://github.com/utkarsh9891/PackageSync) and uninstall st, cleanup the cache of you computer and Install again? Its weird, I never seen that problem and can't reproduce the bug

**Comment by huyle2607** [comment] 2015-12-03 05:53
@equinusocio  It appears with this theme only. However, when I apply some other themes such as Itg.flat, it has some problems too (different problems, not this kind of glitch thing).
Is it because of my ST3?
@Revod  Ok, I'll try your solution.

**Comment by equinusocio** [comment] 2015-12-08 11:54
I will close this issue for now becouse isn't related to material theme.

**Closed by equinusocio** 2015-12-08 11:54 UTC
