### ISSUE TITLE
AppBar issues

### ISSUE THREAD

**Issue by danechitoaie** [equinusocio/material-theme#992] opened 2016-10-04 11:44 UTC
Regarding https://github.com/equinusocio/material-theme/releases I just opened Sublime Today and it autoupdated the theme and the release notes say "Fix sidebar heading color with Appbar Package" but I still have this issue.

<img width="816" alt="screen shot 2016-10-04 at 14 44 10" src="https://cloud.githubusercontent.com/assets/10779010/19072979/0cad7626-8a41-11e6-9780-c742b14f1c72.png">

**Comment by equinusocio** [comment] 2016-10-04 12:55
Same as #991. Update both Material Theme and Material Theme Appbar

**Comment by mattblang** [comment] 2016-10-04 13:15
@equinusocio It looks like this issue is back with `3.2.2`. I had originally saw it in `3.2.0`, then it was fixed in `3.2.1`, but it seems to be back with `3.2.2` this morning. I also have `1.2.4` of the `Material Theme Appbar`.

**Comment by equinusocio** [comment] 2016-10-04 13:22
This is the actual situation on my machines. Try to reactivate the theme and build a new project workspace (Project > New Workspace for project..)

<img width="1034" alt="screen shot 2016-10-04 at 15 21 34" src="https://cloud.githubusercontent.com/assets/10454741/19075681/447b11a8-8a46-11e6-8f55-057b4b785777.png">

**Comment by equinusocio** [comment] 2016-10-04 13:28
I've released (again) a new build (1.2.5). So wait for it and let me know.

**Comment by danechitoaie** [comment] 2016-10-04 13:52
Now I'm on 1.2.4. Waiting for PackageControl to pick the new version and I'll reply back if it's fixed.

**Comment by japborst** [comment] 2016-10-04 15:11
Having the same issue with appbar 1.2.5 and material theme 3.2.2

**Comment by mattblang** [comment] 2016-10-04 15:12
^ Ditto

**Comment by jCrip** [comment] 2016-10-04 15:18
Same here, having the same issue with appbar 1.2.5 and material theme 3.2.2

**Comment by danechitoaie** [comment] 2016-10-04 15:19
Updated to 1.2.5 and material theme 3.2.2 and still same issue.

<img width="1069" alt="screen shot 2016-10-04 at 18 18 20" src="https://cloud.githubusercontent.com/assets/10779010/19080211/0876f104-8a5f-11e6-8d60-c92b78d749cc.png">

**Comment by djekl** [comment] 2016-10-04 16:11
Same issue here also.

```- Sublime Text:   3126
- Platform:   osx
- Arch:   x64
- Theme:   3.2.2
- Install via PC:   True
- Dependencies:
    * mdpopups:   1.10.0
    * markdown:   2.6.6
    * pygments:   2.1a0
    * jinja2:   2.8
``` 

Material Theme - Appbar v1.2.5

**Comment by Guich** [comment] 2016-10-04 16:20
Hi,

the issue is present only if you have setted true the option: "material_theme_small_statusbar".

If you put it false it work fine.

Mattia doesn't have the issue because he don't use the small status bar :)

**Comment by djekl** [comment] 2016-10-04 16:24
Its not a small `"material_theme_small_statusbar": true` that is the problem,  its `"material_theme_small_tab": true`

**Comment by danechitoaie** [comment] 2016-10-04 16:27
Yes, can confirm. With `material_theme_small_tab : false` it works ok.

**Comment by Guich** [comment] 2016-10-04 16:27
@djekl Yeah, sorry, my mistake

**Comment by equinusocio** [comment] 2016-10-04 16:30
Thanks. I will investigate.

**Comment by equinusocio** [comment] 2016-10-04 16:45
I have have no issue using `material_theme_small_tab: true`...

**Comment by equinusocio** [comment] 2016-10-04 16:48
You tried to build a new project workspace (Project > New Workspace for project..)?

**Comment by djekl** [comment] 2016-10-04 16:50
here is my sublime prefrences

```json
{
    "always_prompt_for_file_reload": true,
    "auto_complete_commit_on_tab": true,
    "auto_complete_with_fields": true,
    "bold_folder_labels": true,
    "color_inactive_tabs": true,
    "color_scheme": "Packages/User/SublimeLinter/Monokai (SL).tmTheme",
    "detect_indentation": false,
    "detect_slow_plugins": false,
    "drag_text": false,
    "ensure_newline_at_eof_on_save": true,
    "folder_exclude_patterns":
    [
        ".svn",
        ".git",
        ".sass-cache",
        ".codekit-cache",
        ".hg",
        "CVS"
    ],
    "font_face": "Operator Mono",
    "font_options":
    [
        "no_round",
        "subpixel_antialias"
    ],
    "font_size": 12,
    "highlight_line": true,
    "highlight_modified_tabs": true,
    "ignored_packages":
    [
        "SublimeLinter",
        "SublimeLinter-php",
        "Vintage"
    ],
    "indent_guide_options":
    [
        "draw_normal",
        "draw_active"
    ],
    "line_padding_bottom": 1,
    "line_padding_top": 1,
    "open_files_in_new_window": false,
    "overlay_scroll_bars": true,
    "scroll_past_end": false,
    "shift_tab_unindent": true,
    "show_encoding": true,
    "show_full_path": true,
    "tabs_padding_small": true,
    "tabs_small": true,
    "theme": "Material-Theme-Darker.sublime-theme",
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": true,
    "material_theme_accent_bright-teal": true,
    "material_theme_compact_sidebar": true,
    "material_theme_contrast_mode": true,
    "material_theme_small_statusbar": true,
    "material_theme_tabs_autowidth": true,
    "material_theme_tabs_separator": true,
    "material_theme_tree_headings": true,
    "material_theme_small_tab": true,
    "word_wrap": true
}
```

and my package control prefrences

```json
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"AdvancedNewFile",
		"Alignment",
		"All Autocomplete",
		"Animate.css Snippets",
		"ApacheConf.tmLanguage",
		"API Blueprint",
		"Autoprefixer",
		"Babel",
		"Behat",
		"Behat Features",
		"Behat Snippets",
		"Blade Snippets",
		"Blade Spacer",
		"Bootstrap 3 Snippets",
		"Bower",
		"Case Conversion",
		"CasperJS",
		"cdnjs",
		"CodeComplice",
		"CSS3",
		"DashDoc",
		"Delete Current File",
		"DocBlockr",
		"DotENV",
		"EditorConfig",
		"Ember Template Component Split View",
		"EmberScript",
		"Emmet",
		"Expression",
		"Function Name Display",
		"Git",
		"GitGutter",
		"Gitignore",
		"gitp",
		"GitSavvy",
		"Gutter Color",
		"Handlebars",
		"HTML-CSS-JS Prettify",
		"HTMLAttributes",
		"HTMLBeautify",
		"Image2Base64",
		"Indent XML",
		"Javascript Beautify",
		"JavaScriptNext - ES6 Syntax",
		"jQuery",
		"Laravel 5 Artisan",
		"Laravel 5 Snippets",
		"Laravel Blade Highlighter",
		"Laravel Bootstrapper Snippets",
		"Laravel Color Scheme",
		"LESS",
		"Markdown Extended",
		"Material Theme",
		"Material Theme - Appbar",
		"Monokai Extended",
		"nginx",
		"Package Control",
		"PackageResourceViewer",
		"PHP Companion",
		"PhpSimpleRefactor",
		"PHPUnit Completions",
		"PHPUnit Snippets",
		"Pretty JSON",
		"Puppet",
		"react-native-snippets",
		"ReactJS",
		"ReactJS Snippets",
		"RegReplace",
		"Sass",
		"SassBeautify",
		"SCSS",
		"SCSS Expander",
		"Shell Exec",
		"SideBarEnhancements",
		"SimplePHPUnit",
		"SublimeEnhancedUtilitiesSet",
		"SublimeLinter",
		"SublimeLinter-annotations",
		"SublimeLinter-php",
		"SwapStrings",
		"SyncedSideBar",
		"Theme - Afterglow",
		"Theme - Petroleum",
		"Theme - Soda",
		"Unicode Character Highlighter",
		"Vuejs Complete Package",
		"ZPL Syntax"
	]
}
```

and yes I have tried a new project workspace, still same issue

**Comment by equinusocio** [comment] 2016-10-04 16:57
@djekl is strange, with you preferences i get the issue, and the cause is the small_tab setting. With my preferences i have no issue even with the small_tab setting. I wanna cry :D

**Comment by danechitoaie** [comment] 2016-10-04 17:02
Here's mine.

```
{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"caret_style": "phase",
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"detect_indentation": false,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"material_theme_accent_brba": true,
	"material_theme_appbar_lime": true,
	"material_theme_panel_separator": true,
	"material_theme_small_tab": true,
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
	"theme": "Material-Theme-Darker.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"word_wrap": false
}

```

```
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"AlignTab",
		"BracketHighlighter",
		"DocBlockr",
		"DocBlockr_Python",
		"GitGutter",
		"Material Theme",
		"Material Theme - Appbar",
		"Package Control"
	]
}

```

**Comment by djekl** [comment] 2016-10-04 17:04
@equinusocio at least you now can reproduce it, even if it is with my massive preferences. Start stripping out options, and see what kicks it loose

**Comment by equinusocio** [comment] 2016-10-04 17:06
You can try also with my preferences?
```
{
	"always_show_minimap_viewport": true,
	"auto_complete_commit_on_tab": true,
	"auto_complete_with_fields": true,
	"bold_folder_labels": true,
	"caret_extra_bottom": 0,
	"caret_extra_top": 0,
	"caret_extra_width": 1,
	"caret_style": "phase",
	"close_windows_when_empty": false,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"dictionary": "Packages/Language - English/en_US.dic",
	"draw_white_space": "all",
	"enable_tab_scrolling": false,
	"ensure_newline_at_eof_on_save": true,
	"fade_fold_buttons": true,
	"folder_exclude_patterns":
	[
		".svn",
		".git",
		".sass-cache",
		".idea",
		".hg",
		"CVS"
	],
	"font_face": "Operator Mono",
	"font_options":
	[
		"gray_antialias"
	],
	"font_size": 14,
	"ha_style": "filled",
	"highlight_line": true,
	"ignore_vcs_packages": true,
	"ignored_packages":
	[
		"Color Highlighter",
		"ERB Autocomplete",
		"ERB Snippets",
		"Vintage",
		"vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"index_files": true,
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"material_theme_accent_bright-teal": true,
	"material_theme_appbar_lime": true,
	"material_theme_small_tab": true,
	"overlay_scroll_bars": "enabled",
	"preview_on_click": false,
	"show_encoding": true,
	"show_tab_close_buttons": true,
	"skin": "Material Theme/Material Theme",
	"spell_check": false,
	"tab_size": 2,
	"theme": "Material-Theme.sublime-theme",
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true,
	"use_tab_stops": true,
	"vintage_start_in_command_mode": true,
	"word_wrap": false
}

```

**Comment by equinusocio** [comment] 2016-10-04 17:13
@danechitoaie also with you preference I have the same issue, but if I use `"material_theme_small_tab": true,` with my preferences i don't have any issue...

**Comment by Guich** [comment] 2016-10-04 17:16
@equinusocio those are mine:

{
	"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"close_windows_when_empty": false,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme-Darker.tmTheme",
	"font_face": "Input",
	"font_size": 12,
	"ignored_packages":
	[
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"material_theme_accent_purple": true,
	"material_theme_appbar_purple": true,
	"material_theme_compact_panel": true,
	"material_theme_compact_sidebar": true,
	"material_theme_contrast_mode": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
	"theme": "Material-Theme-Darker.sublime-theme",
	"word_wrap": true
}

I tried to comment a lot of those and nothing... Issue still here...
Anyway, why you've removed the label "Project"?

**Comment by bedatse** [comment] 2016-10-04 17:17
@equinusocio.  Looking into your package, what I have noticed is that the pngs for sidebar_heading / sidebar_heading-small are also missing compared to previous version, was there any change in that area?

**Comment by equinusocio** [comment] 2016-10-04 17:39
@bedatse good point.. this is another issue.

**Comment by bedatse** [comment] 2016-10-04 17:42
@equinusocio when I renamed those asset, something actually turns out in the sidebar header, like this

<img width="458" alt="screen shot 2016-10-05 at 1 42 33 am" src="https://cloud.githubusercontent.com/assets/7496207/19085476/03d8916e-8a9d-11e6-8088-23d020f6ea8c.png">

**Comment by bedatse** [comment] 2016-10-04 18:02
@equinusocio 

Under class "sidebar_container"
setting "layer1.tint" is the line to blame

with this commit
https://github.com/equinusocio/material-theme/commit/d8bebcad2a23e9af4c97c4e2a1beaa03017e1739

I have override this by adding this into Packages/Material Theme - Appbar/Material-Theme-Darker.sublime-theme `"layer1.tint": [],` at row 286, and everything starts to work again
<img width="708" alt="screen shot 2016-10-05 at 2 00 29 am" src="https://cloud.githubusercontent.com/assets/7496207/19086127/859e2afe-8a9f-11e6-8d9b-0e65ffd56d19.png">

**Comment by equinusocio** [comment] 2016-10-04 18:05
Yes, but this line must exist. I found another solution but i need to do some test and some tester. :)

**Comment by bedatse** [comment] 2016-10-04 18:23
<img width="624" alt="screen shot 2016-10-05 at 2 22 29 am" src="https://cloud.githubusercontent.com/assets/7496207/19086888/9b2fbf4c-8aa2-11e6-83df-e6e4da58665c.png">

displaced by somewhat 8-10px

**Comment by equinusocio** [comment] 2016-10-04 19:51
Yes @bedatse. You can check again the develop branch?

**Comment by danechitoaie** [comment] 2016-10-04 21:43
1.2.6 just fixed it for me.

**Comment by japborst** [comment] 2016-10-05 07:03
1.2.6 works fixed it for me as well. Thanks @equinusocio

**Closed** 2016-10-05 07:51 UTC
Labels: bug, help wanted, I want to cry
