### ISSUE TITLE
File icons not showing in side bar (Sublime build 3106)

### ISSUE THREAD

**Issue by phortuin** [equinusocio/material-theme#689] opened 2016-02-24 11:28 UTC
Seems like file icons are not showing up in latest Sublime dev build (3106) w/ latest Material Theme on Mac OSX 10.11.3. I set `material_theme_disable_fileicons` to false. Folder icons are working as expected. Some other settings:

	"theme": "Material-Theme-Darker.sublime-theme",
	"material_theme_compact_sidebar": true,
	"material_theme_disable_fileicons": false,
	"material_theme_panel_separator": true,

I use Monokai Extended as color scheme, but that shouldn't be of influence I suppose.

Ofcourse, this could be a bug in the Sublime build, I haven't checked if other themes with file icons have the same issue. Thanks!

**Comment by equinusocio** [comment] 2016-02-24 11:44
There is some bugs with the last build, also sometimes opened tabs disappear from tab bar.. I need time to investigate but i think there is several bugs inside this build.

**Comment by Garconis** [comment] 2016-02-24 14:45
For me, the sidebar doesn't have any of the styling from the theme anymore.

**Comment by churiart** [comment] 2016-02-24 21:46
I confirm this as well.

**Comment by enragedlemon** [comment] 2016-02-25 01:38
I can confirm both the icons disappearing (though this seems to be happening on other themes I've tried too) and the random disappearance of open tabs when saving theme settings. I presume this is caused by the changed made to how themes and schemes are reloaded on the fly?

**Comment by equinusocio** [comment] 2016-02-25 07:59
It's a ST bug.
https://forum.sublimetext.com/t/dev-build-3106/17982/8?u=revod

**Comment by churiart** [comment] 2016-02-25 08:13
It is fixed in new build 3107.

**Closed** 2016-02-25 08:15 UTC
