### ISSUE TITLE
Syntax highlight dictatorship

### ISSUE THREAD

**Issue by Failure13** [equinusocio/material-theme#712] opened 2016-03-03 08:40 UTC
Could someone please tell me how to remove bypass / turn off this non-sense? (ST3)

![Image of Yaktocat](http://i.imgur.com/bEphvmG.png)

At least make an option to turn it off in future releases, if i missed something.
I like the base of theme, but why the hell should you touch my prefrences of file-based syntax highlight and especially why the fuck should you override it?

Thx for attention.

**Comment by equinusocio** [comment] 2016-03-11 14:29
This will be fixed with the latest 2.0.9

**Closed by equinusocio** 2016-03-11 14:29 UTC

**Comment by simonedavico** [comment] 2016-03-21 08:35
@equinusocio after upgrading to 2.0.9, Material Theme syntax highlight options disappeared for me. 

Looking at this issue it seems it was intended, but is there a way to get them back? It worked ok for me, since I didn't have fancy syntax highlight settings to override.

**Comment by equinusocio** [comment] 2016-03-21 09:11
No, sorry. Custom syntaxes are deprecated form the latest builds.

**Comment by simonedavico** [comment] 2016-03-21 09:46
Thank you for the clarification.
