### ISSUE TITLE
LESS syntax no longer working with Material Theme

### ISSUE THREAD

**Issue by sciascia** [equinusocio/material-theme#713] opened 2016-03-04 01:24 UTC
Hi There, 

We're having a weird issue where LESS syntax highlighting no longer works with Material Theme. We have to manually select it for every file but now LESS is greyed out.

Also, 'Open all with current extension...' no longer works.

Is there a preference or something we need to clear?

Any pointers in the right direction would be much appreciated.

Cheers

Ben

**Comment by paradox41** [comment] 2016-03-06 21:05
This might be related to the fact that `.css` files are picking up the `.less` icon.
<img width="110" alt="screen shot 2016-03-06 at 4 04 29 pm" src="https://cloud.githubusercontent.com/assets/2791730/13557009/37ba6a6e-e3b5-11e5-8791-36bb9636da32.png">

**Comment by danro** [comment] 2016-03-08 03:58
I noticed this recently too, it became so frustrating that I had to stop using material theme :cry: 

Is it necessary to include empty syntax definitions in this theme?

**Comment by christoga** [comment] 2016-03-08 05:44
Stop using material-theme, use atom-material-ui instead.

**Comment by fabienb** [comment] 2016-03-10 20:27
I'm not sure it's an issue with package actually: tried OceanicNext because it had become frustrating to work with this issue and the same happened. 
It seems like Sublime can't recognise .less files anymore... see bottom right corner when you open a file: it's marked as Less (capitalised) and is not properly formatted, but after you select the language again it's then marked as LESS (uppercase) and works as expected. Well, until you reopen it. :(

**Comment by dlosie** [comment] 2016-03-10 20:51
I believe I've figured out the cause of this issue. It appears that the `langs/Less.tmLanguage`file in the theme is overriding the `LESS.tmLanguage` from @danro 's LESS-sublime package. According to the [Sublime Text Unofficial Documentation](http://docs.sublimetext.info/en/latest/extensibility/packages.html#merging-and-order-of-precedence) the order of precedence for packages is as follows:

<img width="645" alt="screen shot 2016-03-10 at 12 41 02 pm" src="https://cloud.githubusercontent.com/assets/207057/13683767/6acd87d2-e6bd-11e5-89a4-32f866fc7482.png">

All that to say, **I was able to solve this issue in two ways by either deleting the `Less.tmLanguage` file from the Material Theme or by moving the LESS package to the `Packages/User` directory**. If the Material Theme and LESS packages are installed in the same directory, the Material Theme files will take precedence and override the LESS files (because of the lexicographical order, which I believe is just alphabetical).

I could be wrong about the mechanics involved, but it seems to have fixed the issue for me. Let me know if it works for you guys. Here is a shot of my current `~/Library/Application Support/Sublime Text 3` directory:

<img width="616" alt="screen shot 2016-03-10 at 12 28 27 pm" src="https://cloud.githubusercontent.com/assets/207057/13683866/fa21e8c4-e6bd-11e5-9586-fac6082f947a.png">

**Comment by fabienb** [comment] 2016-03-10 21:07
@dlosie I have managed to remove the .tmLanguage file from the package as suggested and it worked indeed. I assume this will be reintegrated with the next update so let's hope the issue will be fixed by then. Good spot, thank you.

**Comment by danro** [comment] 2016-03-10 21:11
Thanks for the input here. I'm still wondering if @equinusocio can chime in and help determine if the language file is absolutely necessary to this theme?

We're in the process of renaming the `LESS` syntax to `Less` and having the duplicate syntax will only make this situation worse.

**Comment by FichteFoll** [comment] 2016-03-11 03:13
Same issue in a different theme: https://github.com/lefoy/cyanide-theme/issues/40

**Comment by equinusocio** [comment] 2016-03-11 14:21
I don't have this issue (without langs folder)! So i will relase a minor release today without langs folder.

**Comment by equinusocio** [comment] 2016-03-11 15:19
Someone can check with 2.0.9?

**Comment by dolpox** [comment] 2016-03-11 15:41
Fixed.

**Comment by equinusocio** [comment] 2016-03-11 15:42
#719

**Closed by equinusocio** 2016-03-11 15:42 UTC
