### ISSUE TITLE
Sublime theme & color scheme turn back to default after updates

### ISSUE THREAD

**Issue by timbog80** [equinusocio/material-theme#327] opened 2015-07-12 23:29 UTC
i think the title explains enough. after an update the theme and color scheme turn to default.

**Comment by vluzrmos** [comment] 2015-07-12 23:34
That is annoying on Sublime Text... You can disable auto upgrades.

**Comment by vluzrmos** [comment] 2015-07-12 23:37
Preferences > Package Settings > Package Control > Settings User:
"auto_upgrade": false
or 
"auto_upgrade_ignore": [ "Material Theme" ]

**Comment by timbog80** [comment] 2015-07-13 01:33
why would i want to do that? i still want the updates to update automatically

**Comment by Revod** [comment] 2015-07-13 01:34
@timbog80  This happen in every theme, every update you need to restart st

**Comment by timbog80** [comment] 2015-07-13 02:26
no i never got this with spacegray. when i restart sublime nothing happens

**Comment by sasindumendis** [comment] 2015-07-13 08:04
While the theme updating is in process ST falls back to default theme. This is a normal behavior of the editor. You need to wait until the updating gets completed (the progress can be seen on status bar as a %). When it is completed you will see a dialog pops up acknowledging you that the update has been completed and you need to restart the editor. At this point your active theme should be restored back (with few minor UI glitches). Restarting the editor is recommended to load the theme correctly. 

You might not have noticed it before with other themes due to:
- An update was very small and it got completed real quickly making the falling back to default theme while update in progress and restoring the active theme happened quickly hence not quite noticeable.
- Or the active theme interface was quite similar to the default theme thus the switching was not noticeable.

**Comment by equinusocio** [comment] 2015-07-13 17:00
Seriously, you can't complain for this... open a issue in the ST forum. If you prefer, I could not update more Material Theme to and fix errors. And this is a duplicate of #234

**Comment by timbog80** [comment] 2015-07-13 19:45
got it. take it easy

**Comment by equinusocio** [comment] 2015-07-13 20:53
I'm calm, I'm sorry. But this isn't a theme issue.

**Closed by equinusocio** 2015-07-13 20:53 UTC
