### ISSUE TITLE
Massive performance hit and CPU usage spike with Sublime Text (3)

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [equinusocio/material-theme#1193] opened 2017-10-02 05:38 UTC
### Summary

I noticed while working from home this Friday on my new MacBook Pro (High Sierra) that expected battery life was pretty disappointing. Usually, the culprit is Chrome, which is why I use Safari as much as possible when on batteries.

I fired up Activity Monitor and saw nothing evil except Sublime Text eating around 9% CPU while idle. Not a lot, but enough to be the most energy consuming app since I unplugged from the mains.

I tried some tips off Google, like clearing the index caches, but to no avail. I asked my colleague at the daily standup if he experienced the same, which he did not.

Returning to work this Monday, I checked how my work computer (an older Air with El Capitan) behaved, and here the CPU while idle hovered around ~14% (probably higher than my MBP due to the slower CPU). The ST packages and setup is identical between my home and work computers (I keep them synced). I started disabling packages galore, and saw zero change until I disabled Material Theme. I instantly went from ~14% CPU idling to ~1% idling.

Additionally, I use eslinter to lint my JS code, and with the Material Theme, when I make an editor change, I have to wait a couple of seconds before eslinter is done and gives any warnings. Without Material Theme, eslinter works instantly.

### Expected behavior

Material Theme should perform like any other theme.

### Actual behavior

Material Theme gives a huge performance penalty when linting, and eats about 14x as much idle CPU as the default theme.

### Steps to reproduce

1. Install Material Theme
2. Enable Material Theme
3. Observe CPU idle usage

### Environment

* Operating system and version:
  * [ ] Windows ...
  * [x] Mac OS 10.11 & 10.13
  * [ ] Linux ...
* Sublime Text:
  * Build 3143
* Material Theme release:
  * Latest one as per 2017-10-02 (not sure exactly which version, as I uninstalled it)

**Comment by equinusocio** [comment] 2017-10-02 12:54
https://github.com/equinusocio/material-theme/issues/1128
Plese notice that Material Theme for ST is not under active development since i think that Sublime Text 3 is obsolete compared to Visual Studio Code, Atom and IntelliJ Suite (Material Theme exist for all of these software).

PR Are welcome, but features/improvements are locked for now.

**Comment by mallowigi** [comment] 2017-10-02 14:35
@equinusocio I think you should leave this issue open if you can’t fix it. This way contributors will know there is an issue. Here it looks like the plugin is bug free which it isn’t.

**Comment by equinusocio** [comment] 2017-10-02 16:08
There is no contributors right now

**Comment by mallowigi** [comment] 2017-10-02 16:15
No but people will keep on opening new issues about it. If you left the issue open people will know about the issue and perhaps someone will take a look and fix it. Here you're just shunning it.

**Comment by equinusocio** [comment] 2017-10-02 16:18
Your’re right.

**Comment by equinusocio** [comment] 2017-10-02 16:21
But i hate that a 9000 stars open source repository have no contributors other than me. I prefer let it die.. and let users without this “awesome theme” that no one care about.

**Comment by mallowigi** [comment] 2017-10-02 19:38
Oh come on don't be selfish. There are thousand of downloads a month, and a lot of people use it daily, this is why you get issues all the time. If you don't want to take care of it, just leave it there for people to pick it. At some point someone will fork it and then you can give him ownership.

**Comment by equinusocio** [comment] 2017-10-02 20:27
I’m not selfish. After 2 years no one collaborated with this repo :)

**Comment by mallowigi** [comment] 2017-10-02 20:45
@DanielSmedegaardBuus I couldn't reproduce either. My Sublime stays at 2.4 CPU when idle. Care to show your configuration?

**Comment by sn0wyfall** [comment] 2017-10-03 04:08
@equinusocio I care about it. I'll try my best to work on it in my free time. I'll see when I can commit some time to it!

**Comment by equinusocio** [comment] 2017-10-03 10:59
I will close this issue. Please check this one (reopened) https://github.com/equinusocio/material-theme/issues/1128

**Closed** 2017-10-03 11:59 UTC
