### ISSUE TITLE
Sass class highlight

### ISSUE THREAD

**Issue by ilicmarko** [equinusocio/material-theme#812] opened 2016-05-11 08:59 UTC
From a recent update I lost my sass syntax highlighting, classes are not highlighted and id's are highlighted like classes.

![syntax](https://cloud.githubusercontent.com/assets/2827249/15175594/5ac8dbc2-1767-11e6-9286-e49f781df03c.PNG)

**Comment by ivancuric** [comment] 2016-05-11 09:02
Probably a duplicate of https://github.com/equinusocio/material-theme/issues/783

**Comment by ilicmarko** [comment] 2016-05-11 09:08
I am using the using the textmate bundle

https://github.com/MarioRicalde/SCSS.tmbundle

**Comment by equinusocio** [comment] 2016-05-11 09:18
@ilicmarko `....Now Compatible with SublimeText 2.`

Material Theme support Sublime Text 3 build 3103+
Please use https://github.com/nathos/sass-textmate-bundle

**Closed by equinusocio** 2016-05-11 09:18 UTC
