### ISSUE TITLE
Visible Border Project Sidebar

### ISSUE THREAD

**Issue by imoby** [equinusocio/material-theme#377] opened 2015-07-27 05:36 UTC
It is hard to differentiate between the border of the project sidebar and the actual editor. Maybe add some visible border or line to differentiate between them.

**Comment by equinusocio** [comment] 2015-07-27 12:40
You don't have to see the different between sidebar and code. This is distracting. Duplicate of #57

**Closed** 2015-07-27 12:41 UTC
